latexdiff template, latexmk options, spacing
 - corrected spacing (no more tabs)
 - latexmk now also includes the pdflatex options
 - a "type" option can be passed to git-latexdiff (see the latexdiff
   manpage for details)

diff --git a/git-latexdiff b/git-latexdiff
--- a/git-latexdiff
+++ b/git-latexdiff
@@ -93,6 +93,7 @@ Options:
                              (enabled by default, disable with --whole-tree)
     --whole-tree          checkout the whole tree (contrast with --subtree)
     --ignore-makefile     ignore the Makefile, build as though it doesn't exist
+    --type            latexdiff type [default: UNDERLINE]
 EOF
 }
 
@@ -103,25 +104,25 @@ die () {
 
 verbose () {
     if test "$verbose" = 1 ; then
-	printf "%s ..." "$@"
+        printf "%s ..." "$@"
     fi
 }
 
 verbose_progress () {
     if test "$verbose" = 1 ; then
-	printf "." "$@"
+        printf "." "$@"
     fi
 }
 
 verbose_done () {
     if test "$verbose" = 1 ; then
-	echo " ${1:-done}."
+        echo " ${1:-done}."
     fi
 }
 
 verbose_say () {
     if test "$verbose" = 1 ; then
-	printf "%s\n" "$@"
+        printf "%s\n" "$@"
     fi
 }
 
@@ -142,84 +143,85 @@ uselatexmk=
 latexopt=
 ln_untracked=0
 quiet=0
+latexdiff_type=UNDERLINE
 
 while test $# -ne 0; do
     case "$1" in
         "--help"|"-h")
-            usage
-            exit 0
+           usage
+           exit 0
+           ;;
+        "--main")
+            test $# -gt 1 && shift || die "missing argument for $1"
+            main=$1
             ;;
-	"--main")
-	    test $# -gt 1 && shift || die "missing argument for $1"
-	    main=$1
-	    ;;
-	"--no-view")
-	    view=0
-	    ;;
-	"--view")
-	    view=1
-	    ;;
-	"--pdf-viewer")
-	    test $# -gt 1 && shift || die "missing argument for $1"
-	    PDFVIEWER="$1"
-	    ;;
-	"--no-cleanup")
-	    cleanup=none
-	    ;;
+        "--no-view")
+            view=0
+            ;;
+        "--view")
+            view=1
+            ;;
+        "--pdf-viewer")
+            test $# -gt 1 && shift || die "missing argument for $1"
+            PDFVIEWER="$1"
+            ;;
+        "--no-cleanup")
+            cleanup=none
+            ;;
         "--cleanup")
-            shift
-            case "$1" in
-                "none"|"all"|"keeppdf")
-                    cleanup="$1"
-                    ;;
-                *)
-                    echo "Bad argument --cleanup $1"
-                    usage
-                    exit 1
-                    ;;
-            esac
+           shift
+           case "$1" in
+               "none"|"all"|"keeppdf")
+                   cleanup="$1"
+                   ;;
+               *)
+                   echo "Bad argument --cleanup $1"
+                   usage
+                   exit 1
+                   ;;
+           esac
+           ;;
+        "--ignore-makefile")
+            ignoremake=1
             ;;
-	"--ignore-makefile")
-	    ignoremake=1
-	    ;;
-	"-o"|"--output")
-	    test $# -gt 1 && shift || die "missing argument for $1"
-	    output=$1
-	    cleanup=all
-	    ;;
-	"-b"|"--bibtex")
-	    bibtex=1
-	    ;;
-	"--biber")
-	    biber=1
-	    ;;
-	"--verbose"|"-v")
-	    verbose=1
-	    ;;
+        "-o"|"--output")
+            test $# -gt 1 && shift || die "missing argument for $1"
+            output=$1
+            cleanup=all
+            ;;
+        "-b"|"--bibtex")
+            bibtex=1
+            ;;
+        "--biber")
+            biber=1
+            ;;
+        "--verbose"|"-v")
+            verbose=1
+            ;;
         "--quiet")
-	    quiet=1
-	    ;;
-	"--version")
-	    echo "$git_latexdiff_version"
+            quiet=1
+            ;;
+        "--version")
+            echo "$git_latexdiff_version"
             exit 0
-	    ;;
-	"--subtree")
-	    subtree=1
-	    ;;
-	"--whole-tree")
-	    subtree=0
-	    ;;
-	"--prepare")
-	    shift
-	    prepare_cmd="$1"
-	    ;;
+            ;;
+        "--subtree")
+            subtree=1
+            ;;
+        "--whole-tree")
+            subtree=0
+            ;;
+        "--prepare")
+            shift
+            prepare_cmd="$1"
+            ;;
         "--latexmk")
             uselatexmk=1
             ;;
-	"--latexopt")
-	    shift
-	    latexopt=$1
-	    ;;
+        "--latexopt")
+            shift
+            latexopt=$1
+            ;;
         "--ln-untracked")
             ln_untracked=1
             ;;
@@ -227,24 +229,28 @@ while test $# -ne 0; do
             ln_untracked=0
             ;;
         "--tmpdirprefix")
-	    shift
-	    tmpdir_prefix="$1"
-	    ;;
-        *)
-	    if test -z "$1" ; then
-		echo "Empty string not allowed as argument"
-		usage
-		exit 1
-	    elif test -z "$old" ; then
-		old=$1
-	    elif test -z "$new" ; then
-		new=$1
-	    else
-		echo "Bad argument $1"
-		usage
-		exit 1
-	    fi
+            shift
+            tmpdir_prefix="$1"
             ;;
+        "--type")
+            shift
+            latexdiff_type=$1
+            ;;
+        *)
+            if test -z "$1" ; then
+                echo "Empty string not allowed as argument"
+                usage
+                exit 1
+            elif test -z "$old" ; then
+                old=$1
+            elif test -z "$new" ; then
+                new=$1
+            else
+                echo "Bad argument $1"
+                usage
+                exit 1
+            fi
+                ;;
     esac
     shift
 done
@@ -267,33 +273,33 @@ if test -z "$PDFVIEWER" ; then
     candidates="xdg-open evince okular xpdf acroread"
     if test "$(uname)" = Darwin ; then
         # open exists on GNU/Linux, but does not open PDFs
-	candidates="open $candidates"
+        candidates="open $candidates"
     fi
 
     for command in $candidates; do
-	if command -v "$command" >/dev/null 2>&1; then
-	    PDFVIEWER="$command"
-	    break
-	else
-	    verbose_progress
-	fi
+        if command -v "$command" >/dev/null 2>&1; then
+            PDFVIEWER="$command"
+            break
+        else
+            verbose_progress
+        fi
     done
     verbose_done "$PDFVIEWER"
 fi
 
 case "$view" in
     maybe|1)
-	if test -z "$PDFVIEWER" ; then
-	    echo "warning: could not find a PDF viewer on your system."
-	    echo "warning: Please set \$PDFVIEWER or use --pdf-viewer CMD."
-	    PDFVIEWER=false
-	fi
-	;;
+        if test -z "$PDFVIEWER" ; then
+            echo "warning: could not find a PDF viewer on your system."
+            echo "warning: Please set \$PDFVIEWER or use --pdf-viewer CMD."
+            PDFVIEWER=false
+        fi
+        ;;
 esac
 
 check_knitr () {
     if test -z "$prepare_cmd"; then
-	prepare_cmd="Rscript -e \"library(knitr); knit('$main')\""
+        prepare_cmd="Rscript -e \"library(knitr); knit('$main')\""
     fi
     main="${main%\.*}.tex"
 }
@@ -302,9 +308,9 @@ log_cmd () {
     log=$1
     shift
     if [ "$quiet" = 1 ]; then
-	"$@" >$log 2>&1
+        "$@" >$log 2>&1
     else
-	"$@"
+        "$@"
     fi
 }
 
@@ -313,15 +319,15 @@ if test -z "$main" ; then
     main=$(git grep -l '^[ \t]*\\documentclass')
     # May return multiple results, but if so the result won't be a file.
     if test -r "$main" ; then
-	echo "Using $main as the main file."
+        echo "Using $main as the main file."
     else
-	if test -z "$main" ; then
-	    echo "No candidate for main file."
-	else
-	    echo "Multiple candidates for main file:"
-	    printf "%s\n" "$main" | sed 's/^/\t/'
-	fi
-	die "Please, provide a main file with --main FILE.tex."
+        if test -z "$main" ; then
+            echo "No candidate for main file."
+        else
+            echo "Multiple candidates for main file:"
+            printf "%s\n" "$main" | sed 's/^/\t/'
+        fi
+        die "Please, provide a main file with --main FILE.tex."
     fi
 fi
 
@@ -395,7 +401,7 @@ done
 
 verbose "Running latexdiff --flatten old/$main new/$main > ./diff.tex"
 
-latexdiff --flatten old/"$main" new/"$main" > diff.tex || die "latexdiff failed"
+latexdiff -t $latexdiff_type --flatten old/"$main" new/"$main" > diff.tex || die "latexdiff failed"
 
 verbose "mv ./diff.tex new/$main"
 
@@ -409,24 +415,29 @@ maindir=$(dirname "$main")
 
 verbose "Compiling result"
 
+if [ "$quiet" = 1 ]; then
+        latexopt="$latexopt -interaction=nonstopmode"
+else
+        latexopt="$latexopt -interaction=errorstopmode"
+fi
+
 compile_error=0
 cd new/"$maindir" || die "Can't cd to new/$maindir"
 if test -f Makefile && test "$ignoremake" != 1 ; then
     log_cmd make.log make || compile_error=1
 elif test "$uselatexmk" = 1; then
-    log_cmd latexmk.log latexmk -f -pdf -silent "$mainbase" || compile_error=1
+        latexmk_opt="-f -pdf"
+        if test "$quiet" = 1 ; then
+            latexmk_opt="$latexmk_opt -silent"
+        fi
+    log_cmd latexmk.log latexmk -e "\$pdflatex = \"pdflatex $latexopt\"" $latexmk_opt "$mainbase" || compile_error=1
 else
-    if [ "$quiet" = 1 ]; then
-	latexopt="$latexopt -interaction=nonstopmode"
-    else
-	latexopt="$latexopt -interaction=errorstopmode"
-    fi
     log_cmd pdflatex1.log pdflatex $latexopt "$mainbase" || compile_error=1
     if test "$bibtex" = 1 ; then
-	log_cmd bibtex.log bibtex "$mainbase" || compile_error=1
+        log_cmd bibtex.log bibtex "$mainbase" || compile_error=1
     fi
     if test "$biber" = 1 ; then
-	log_cmd biber.log biber "$mainbase" || compile_error=1
+        log_cmd biber.log biber "$mainbase" || compile_error=1
     fi
     log_cmd pdflatex2.log pdflatex $latexopt "$mainbase" || compile_error=1
     log_cmd pdflatex3.log pdflatex $latexopt "$mainbase" || compile_error=1
@@ -470,16 +481,16 @@ fi
 
 case "$cleanup" in
     "all")
-	verbose "Cleaning-up result"
-	rm -fr "$tmpdir"
-	verbose_done
-	;;
+        verbose "Cleaning-up result"
+        rm -fr "$tmpdir"
+        verbose_done
+        ;;
     "keeppdf")
-	verbose "Cleaning-up all but pdf (kept in $pdffile)"
-	rm -fr "$tmpdir"/old "$tmpdir"/new
-	verbose_done
-	;;
+        verbose "Cleaning-up all but pdf (kept in $pdffile)"
+        rm -fr "$tmpdir"/old "$tmpdir"/new
+        verbose_done
+        ;;
     "none")
-	verbose_say "Generated files kept in $tmpdir/"
-	;;
+        verbose_say "Generated files kept in $tmpdir/"
+        ;;
 esac
